/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-07-06 17:09:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("jar:file:/C:/Users/KimYeonJi/Documents/github/Board_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Board/WEB-INF/lib/spring-webmvc-5.2.15.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1620767206000L));
    _jspx_dependants.put("jar:file:/C:/Users/KimYeonJi/Documents/github/Board_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Board/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.15.RELEASE.jar", Long.valueOf(1624893839306L));
    _jspx_dependants.put("/WEB-INF/views/layout/head.jsp", Long.valueOf(1625565419281L));
    _jspx_dependants.put("jar:file:/C:/Users/KimYeonJi/Documents/github/Board_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Board/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/layout/script.jsp", Long.valueOf(1625565419283L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1608061093185L));
    _jspx_dependants.put("/WEB-INF/views/layout/mobile-nav-toggle.jsp", Long.valueOf(1624926975028L));
    _jspx_dependants.put("jar:file:/C:/Users/KimYeonJi/Documents/github/Board_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Board/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/layout/footer.jsp", Long.valueOf(1625565419280L));
    _jspx_dependants.put("/WEB-INF/views/layout/header_sidebar2.jsp", Long.valueOf(1625508855764L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\r');
            out.write('\n');
            out.write('	');
            if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("	\r\n");
            out.write("	");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f0_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\r\n");
                  out.write("<!DOCTYPE html>\r\n");
                  out.write("<html lang=\"kr\">\r\n");
                  out.write("<head>\r\n");
                  out.write("	");
                  out.write("\r\n");
                  out.write("    \r\n");
                  out.write("  <meta charset=\"utf-8\">\r\n");
                  out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
                  out.write("\r\n");
                  out.write("<!-- 웹 사이트 이름 -->\r\n");
                  out.write("  <title>Y - Spring</title>\r\n");
                  out.write("  <meta content=\"\" name=\"description\">\r\n");
                  out.write("  <meta content=\"\" name=\"keywords\">\r\n");
                  out.write("\r\n");
                  out.write("  <!-- Favicons 파비콘 -->\r\n");
                  out.write("  <link rel=\"icon\" href=\"/resources/assets/img/favicon.ico\">\r\n");
                  out.write("\r\n");
                  out.write("  <!-- Google Fonts -->\r\n");
                  out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
                  out.write("\r\n");
                  out.write("  <!-- Vendor CSS Files -->\r\n");
                  out.write("  <link href=\"/resources/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
                  out.write("  <link href=\"/resources/assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\r\n");
                  out.write("  <link href=\"/resources/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
                  out.write("  <link href=\"/resources/assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\r\n");
                  out.write("  <link href=\"/resources/assets/vendor/owl.carousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
                  out.write("  <link href=\"/resources/assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
                  out.write("\r\n");
                  out.write("  <!-- Template Main CSS File -->\r\n");
                  out.write("  <link href=\"/resources/assets/css/style.css\" rel=\"stylesheet\">\r\n");
                  out.write("\r\n");
                  out.write("  <!-- =======================================================\r\n");
                  out.write("  * Template Name: MyResume - v2.2.1\r\n");
                  out.write("  * Template URL: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/\r\n");
                  out.write("  * Author: BootstrapMade.com\r\n");
                  out.write("  * License: https://bootstrapmade.com/license/\r\n");
                  out.write("  ======================================================== -->\r\n");
                  out.write("  \r\n");
                  out.write("\r\n");
                  out.write("\r\n");
                  out.write("\r\n");
                  out.write("	<link href=\"/resources/board/boardStyle.css\" rel=\"stylesheet\">\r\n");
                  out.write("	\r\n");
                  out.write("	<script>\r\n");
                  out.write("		function chkDelete(b_id){\r\n");
                  out.write("			// 삭제 여부, 다시 확인하고 진행하기\r\n");
                  out.write("			var r = confirm(\"삭제하시겠습니까?\");\r\n");
                  out.write("			\r\n");
                  out.write("			if(r){\r\n");
                  out.write("				location.href = 'deleteOk?b_id=' + b_id;\r\n");
                  out.write("			}\r\n");
                  out.write("		}\r\n");
                  out.write("	</script>\r\n");
                  out.write("</head>\r\n");
                  out.write("\r\n");
                  out.write("<body>\r\n");
                  out.write("\r\n");
                  out.write("  <!-- ======= Mobile nav toggle button ======= -->\r\n");
                  out.write("  ");
                  out.write("\r\n");
                  out.write("    \r\n");
                  out.write("    <!-- ======= Mobile nav toggle button ======= -->\r\n");
                  out.write("  <button type=\"button\" class=\"mobile-nav-toggle d-xl-none\"><i class=\"icofont-navigation-menu\"></i></button>");
                  out.write("\r\n");
                  out.write(" \r\n");
                  out.write("  <!-- ======= Header ======= 왼쪽 정렬해 놓은 메뉴들 -->\r\n");
                  out.write("  ");
                  out.write("\r\n");
                  out.write("<!-- ======= Header ======= 왼쪽 정렬해 놓은 메뉴들 -->\r\n");
                  out.write("  <header id=\"header\" class=\"d-flex flex-column justify-content-center\">\r\n");
                  out.write(" <nav class=\"nav-menu\">\r\n");
                  out.write("      <ul class=\"navUl\">\r\n");
                  out.write("      	<!-- class=\"active\"을 통해 메뉴를 눌렀을때 해당 구간으로 이동 + 색 변화 -->\r\n");
                  out.write("        <li class=\"nav-home\"><a href=\"");
                  out.print(request.getContextPath());
                  out.write("/index\"><i class=\"bx bx-home\"></i> <span>Home</span></a></li>\r\n");
                  out.write("        <li class=\"active nav-board\"><a href=\"");
                  out.print(request.getContextPath());
                  out.write("/board/list\"><i class=\"bx bx-conversation\"></i> <span>QnA</span></a></li>\r\n");
                  out.write("        <li class=\"nav-user\"><a href=\"#user\"><i class=\"bx bx-user\"></i> <span>User</span></a></li>\r\n");
                  out.write("      </ul>\r\n");
                  out.write("    </nav><!-- .nav-menu -->\r\n");
                  out.write("\r\n");
                  out.write("  </header><!-- End Header -->");
                  out.write("\r\n");
                  out.write("\r\n");
                  out.write("  <!-- ======= content Section ======= -->\r\n");
                  out.write("	<main id=\"main\">\r\n");
                  out.write("		<div id=\"content\">\r\n");
                  out.write("			<div id=\"QnA\" class=\"QnA\">\r\n");
                  out.write("				<div class=\"container\" data-aos=\"fade-up\">\r\n");
                  out.write("					<div class=\"content-title\">\r\n");
                  out.write("						<h2>Tech</h2>\r\n");
                  out.write("					</div>\r\n");
                  out.write("					<!-- 글작성 card -->\r\n");
                  out.write("					<div class=\"card\">\r\n");
                  out.write("						<div class=\"card-header\">\r\n");
                  out.write("							<div style=\"float: left\">\r\n");
                  out.write("								<h5 class=\"card-title mb-0\">READ</h5>\r\n");
                  out.write("							</div>\r\n");
                  out.write("							<div style=\"float: right\">\r\n");
                  out.write("								<button type=\"button\" class=\"btn btn-outline-success btn-xs btn-radius\" onclick=\"history.back()\">←</button>\r\n");
                  out.write("							</div>\r\n");
                  out.write("						</div>\r\n");
                  out.write("						<div class=\"card-body\">\r\n");
                  out.write("							<form name=\"frm\" action=\"writeOk\" method=\"post\" onsubmit=\"\">\r\n");
                  out.write("								<div class=\"row\">\r\n");
                  out.write("									<div class=\"col-md-12\">\r\n");
                  out.write("										<!-- 글제목 -->\r\n");
                  out.write("										<div class=\"mb-3\">\r\n");
                  out.write("											<div class=\"row\">\r\n");
                  out.write("												<div class=\"form-label col-md-2 text-center font-weight-bold\" for=\"inputTitle\">제목</div>\r\n");
                  out.write("												<div id=\"minCenter\" class=\"col-md-10 minCenterc\">");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].b_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</div>\r\n");
                  out.write("											</div>\r\n");
                  out.write("										</div>\r\n");
                  out.write("										<!-- 작성자 -->\r\n");
                  out.write("										<div class=\"mb-3\">\r\n");
                  out.write("											<div class=\"row\">\r\n");
                  out.write("												<div class=\"form-label col-md-2 text-center font-weight-bold\" for=\"inputrRegname\">작성자</div>\r\n");
                  out.write("												<!-- 수정자 유무 -->\r\n");
                  out.write("												");
                  if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
                    return;
                  out.write("\r\n");
                  out.write("											</div>\r\n");
                  out.write("										</div>\r\n");
                  out.write("										<!-- 글내용 -->\r\n");
                  out.write("										<div class=\"mb-3\">\r\n");
                  out.write("											\r\n");
                  out.write("												<div class=\"form-label pl-0 col-md-2 col-2 text-center font-weight-bold\" for=\"inputContent\">내용</div>\r\n");
                  out.write("												<br>\r\n");
                  out.write("												<div class=\"m-3 p-3\" style=\"border:1px dashed rgba(0,0,0,.125)\">");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].b_content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</div>\r\n");
                  out.write("											\r\n");
                  out.write("										</div>\r\n");
                  out.write("									</div>\r\n");
                  out.write("								</div>\r\n");
                  out.write("\r\n");
                  out.write("							</form>\r\n");
                  out.write("						</div>\r\n");
                  out.write("					</div>\r\n");
                  out.write("					<br>\r\n");
                  out.write("					<div class=\"btnDivCenter\">\r\n");
                  out.write("						<button type=\"button\" class=\"btn btn-outline-warning btn-sm btn-radius\" onclick=\"location.href='update?b_id=");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].b_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("'\">수정하기</button>\r\n");
                  out.write("						");
                  out.write("\r\n");
                  out.write("					</div>\r\n");
                  out.write("			</div>\r\n");
                  out.write("		</div>\r\n");
                  out.write("		</div>\r\n");
                  out.write("	</main>\r\n");
                  out.write("	<!-- ======= Footer ======= -->\r\n");
                  out.write("  ");
                  out.write("\r\n");
                  out.write("    \r\n");
                  out.write("    \r\n");
                  out.write("    <!-- 오른쪽하단에 ↑ 화살표-->\r\n");
                  out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"bx bx-up-arrow-alt\"></i></a>\r\n");
                  out.write("  \r\n");
                  out.write("  <!-- 페이징 로딩 -->\r\n");
                  out.write("  <div id=\"preloader\"></div>\r\n");
                  out.write("    \r\n");
                  out.write("<!-- ======= Footer ======= -->\r\n");
                  out.write("  <footer id=\"footer\">\r\n");
                  out.write("    <div class=\"container\">\r\n");
                  out.write("      <h3>Spring is coming</h3>\r\n");
                  out.write("      <p>No winter lasts forever. No spring skips its turn.</p>\r\n");
                  out.write("      <div class=\"social-links\">\r\n");
                  out.write("        <a href=\"#\" class=\"twitter\"><i class=\"bx bxl-twitter\"></i></a>\r\n");
                  out.write("        <a href=\"#\" class=\"facebook\"><i class=\"bx bxl-facebook\"></i></a>\r\n");
                  out.write("        <a href=\"#\" class=\"instagram\"><i class=\"bx bxl-instagram\"></i></a>\r\n");
                  out.write("        <a href=\"#\" class=\"google-plus\"><i class=\"bx bxl-skype\"></i></a>\r\n");
                  out.write("        <a href=\"#\" class=\"linkedin\"><i class=\"bx bxl-linkedin\"></i></a>\r\n");
                  out.write("      </div>\r\n");
                  out.write("      <div class=\"copyright\">\r\n");
                  out.write("        &copy; Copyright <strong><span>MyResume</span></strong>. All Rights Reserved\r\n");
                  out.write("      </div>\r\n");
                  out.write("      <div class=\"credits\">\r\n");
                  out.write("        <!-- All the links in the footer should remain intact. -->\r\n");
                  out.write("        <!-- You can delete the links only if you purchased the pro version. -->\r\n");
                  out.write("        <!-- Licensing information: [license-url] -->\r\n");
                  out.write("        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/ -->\r\n");
                  out.write("        Designed by <a href=\"https://github.com/KINyonji\">Kimyonji</a>\r\n");
                  out.write("      </div>\r\n");
                  out.write("    </div>\r\n");
                  out.write("  </footer><!-- End Footer -->");
                  out.write("\r\n");
                  out.write("\r\n");
                  out.write("  <!-- Vendor JS Files -->\r\n");
                  out.write("  ");
                  out.write("\r\n");
                  out.write("<!-- Vendor JS Files -->\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/jquery/jquery.min.js\"></script>\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/php-email-form/validate.js\"></script>\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/counterup/counterup.min.js\"></script>\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/venobox/venobox.min.js\"></script>\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/typed.js/typed.min.js\"></script>\r\n");
                  out.write("  <script src=\"/resources/assets/vendor/aos/aos.js\"></script>\r\n");
                  out.write("\r\n");
                  out.write("  <!-- Template Main JS File -->\r\n");
                  out.write("  <script src=\"/resources/assets/js/main.js\"></script>\r\n");
                  out.write("  \r\n");
                  out.write("\r\n");
                  out.write("    <!-- DataTable -->\r\n");
                  out.write("	<link rel=\"stylesheet\" href=\"https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css\" />\r\n");
                  out.write("	<script  src=\"https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js\"></script>\r\n");
                  out.write("	\r\n");
                  out.write("  	<!--  jquery validate --> \r\n");
                  out.write(" 	<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js\"></script>\r\n");
                  out.write("\r\n");
                  out.write("     \r\n");
                  out.write("\r\n");
                  out.write("	");
                  out.write("\r\n");
                  out.write("\r\n");
                  out.write("</body>\r\n");
                  out.write("</html>\r\n");
                  out.write("\r\n");
                  out.write("	");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
              _jspx_th_c_005fotherwise_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
            }
            out.write('\r');
            out.write('\n');
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/board/boardView.jsp(10,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty list || fn:length(list) == 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<script>\r\n");
          out.write("			alert(\"해당 정보가 삭제되거나 없습니다.\");\r\n");
          out.write("			history.back();\r\n");
          out.write("		</script>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("									\r\n");
          out.write("													");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("										\r\n");
          out.write("													");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/board/boardView.jsp(81,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty list[0].u_modifyname }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("														<div id=\"minCenter\" class=\"col-md-10\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].u_regname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("													");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("														<div id=\"minCenter\" class=\"col-md-10\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].u_modifyname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("													");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
